version: '3.8'

services:
  card-validation-service:
    build:
      context: .  # Build the Dockerfile in the current directory
    ports:
      - "8080:8080"  # Map container's port 8080 to host's port 8080
    container_name: card_validation_service  # Name the container for easier reference
    restart: unless-stopped  # Restart policy